In [ ]:
#  Python 3 and Numpy tutorial from
#  http://cs231n.github.io/python-numpy-tutorial/
#  It was included with Stanford University's
#  "convolutional Neural Network" course
#  http://cs231n.stanford.edu/

In [ ]:
##  List defined using        []     ->[a,b,c,d,e...]
##  Dictionary defined using  {a:b,} ->  {a:b, c:d,}
##  Set defined using         {}     ->  {a,b,c,d,e...}
##  Tuple defined using       ()     ->  (a,b,c,d,e,f...)

## List - can use enumerate(list)    IS ORDERED
## Dictionary - can dictionary.items():
## Set - can use enumerate(set)      NOT ORDERED
## Tuple - can use enumerate


In [7]:
# integer and floats
x = 3
print(type(x))
print(x)
print(x+1)
y = 2.0
print(type(y))
print(y)
print(x+y)

<class 'int'>
3
4
<class 'float'>
2.0
5.0


In [8]:
# Boolean logic
t = True
f = False
print(type(t))
print(t and f)
print(t or f)
print(not t)
print(t !=f)

<class 'bool'>
False
True
False
True


In [9]:
# Strings
hello = 'hello'
world = "world"
print(hello)
print(len(hello))
hw = hello + " " + world
print(hw)
hw12 = '%s %s %d' % (hello, world, 12)   # sprintf style string format
print(hw12)

hello
5
hello world
hello world 12


In [10]:
# String object methods
s = "hello"
print(s.capitalize())
print(s.upper())
print(s.rjust(7))
print(s.center(7))
print(s.replace('l', '(ell)'))
print('  world '.strip())


Hello
HELLO
  hello
 hello 
he(ell)(ell)o
world


## List 

In [2]:
# List Container
# List is equivalent of an array but is resizable and
# can contain elements of different types
xs = [3, 1, 2]
print(type(xs))
print(len(xs))
print(type(xs[0]))
print(xs, xs[2])
print(xs[-1])
print(xs[-3])
xs[2]="foo"
print(xs)
xs.append("bar")
print(xs)
x = xs.pop()
print(x,xs)

<class 'list'>
3
<class 'int'>
[3, 1, 2] 2
2
3
[3, 1, 'foo']
[3, 1, 'foo', 'bar']
bar [3, 1, 'foo']


In [33]:
# List Slicing
nums = list(range(5))
print(nums)
print(nums[2:])
print(nums[:2])
print(nums[:])
print(nums[:-1])
nums[2:4] = [8,9]
print(nums)

# The classes appear to be  "range" and "list". 
# List can take a range as a constructor
# Slicing is an operator on List with [x:y]  (inclusive:exclusive)
x=list(range(1,5))
print(x[2])
print(x[1:3])

[0, 1, 2, 3, 4]
[2, 3, 4]
[0, 1]
[0, 1, 2, 3, 4]
[0, 1, 2, 3]
[0, 1, 8, 9, 4]
3
[2, 3]


In [94]:
# List - loop traditional
animals =[ "cat", "dog", "monkey"]
for a in animals:
    print(a)

# List - loop using "enumerate"
for idx,animal in enumerate(animals):
    print('%d: %s' % (idx + 1, animal))

# Comprehension using one list to create another List
nums = [1,2,3,5,6]
numsSquared = [x ** 2 for x in nums if x%2 == 0 ]
print(numsSquared)

cat
dog
monkey
1: cat
2: dog
3: monkey
[4, 36]


## Dictionary
https://docs.python.org/3.5/library/stdtypes.html#dict

In [16]:
# Dictionary
d = {'cat':"cute", "dog": "furry", "car": 5}
print(type(d))
print(len(d))
print(d.keys())

print(d["cat"])
print("cat" in d)
print(d.get("monkey","yowza!"))
#d.add({8:"blah", 2.3:"foo", "bar":3.2})

<class 'dict'>
3
dict_keys(['dog', 'cat', 'car'])
cute
True
yowza!


In [95]:
# Dictionary - loop traditional
d = {"person": 2, "cat":4, "spider": 8}
for animal in d:
    legs = d[animal]
    print("%s has %d legs" % (animal, legs))
    
# Dictionary - loop using .items()
d = {"person": 2, "cat":4, "spider":8}
for animal,legs in d.items():
    print("%s has %d legs" % (animal, legs))
    
# Comprehension on a list to create a Dictionary
nums = [0,1,2,3,3,4,4]
even_num_to_square = {x: x+10 for x in nums if x==3}
print(even_num_to_square)

cat has 4 legs
spider has 8 legs
person has 2 legs
cat has 4 legs
spider has 8 legs
person has 2 legs
{3: 13}


In [100]:
# Set
# a Set is an unordered collection of distinct elements.
animals = {"cat", "dog", "fish"}
animals.add("bird")
print("fish" in animals)
print(len(animals))

# Set - loop traditional
for a in animals:
    print(a)
    
# Set - loop using "enumerate"
for idx,an in enumerate(animals):
    print("%d -> %s" % (idx,an))
    
# Comprehension on a list to create a Set
#from math import sqrt
nums = {x/2    for x in range(10) }
print(nums)
nums = {x    for x in range(30)   if x>25 or x<3 }
print(nums)


True
4
dog
bird
cat
fish
0 -> dog
1 -> bird
2 -> cat
3 -> fish
{0.0, 0.5, 2.0, 2.5, 1.0, 1.5, 3.0, 3.5, 4.0, 4.5}
{0, 1, 2, 26, 27, 28, 29}


In [110]:
# Tuple
# A Tuple is an immutable ordered list of values.
# Can be used as keys in a dictionary and as elements of sets.

# create dictionary w tuple keys that are ordered list of values
d = { (x, x+1): x for x in range(10)} 
print(d)

t = (5,6) # create a tuple
print(type(t))
print(d[t])  # access the dictionary using the tuple
print(d[1,2])

t2 = (1,2,3,4)
t3 = (2,3,4,5)
print(t2)

# List - loop using "enumerate"
for a,b in enumerate(t2):
    print('%d: %d' % (a, b))

# Comprehension using one list to create another List
y = [x for x in t2 ]
print(y)

{(0, 1): 0, (1, 2): 1, (5, 6): 5, (2, 3): 2, (4, 5): 4, (6, 7): 6, (8, 9): 8, (9, 10): 9, (3, 4): 3, (7, 8): 7}
<class 'tuple'>
5
1
(1, 2, 3, 4)
0: 1
1: 2
2: 3
3: 4
[1, 2, 3, 4]


# Python Functions

In [113]:
# Functions are defined using "def"
def sign(x):
    if x>0:
        return "positive"
    elif x<0:
        return "negative"
    else:
        return "zero"

for x in [-1, 0, 1]:
    print(sign(x))
    
    
def hello(name, loud=False):
    if loud:
        print("HELLO, %s!" % name.upper())
    else:
        print("Hello, %s" % name)

hello("Bob")
hello("Fred", loud=True)


negative
zero
positive
Hello, Bob
HELLO, FRED!


# Python Classes 

In [178]:
# Classes are defined using "class"
# The syntax is:
class Greeter(object):
    # Constructor
    def __init__(self,name):
        self.name = name
    
    # Instance method
    def greet(self,loud=False):
        if loud:
            print("HELLO, %s!" % self.name.upper())
        else:
            print("Hello, %s" % self.name)

g = Greeter('Fred')
g.greet()
g.greet(loud=True)


Hello, Fred
HELLO, FRED!


# Numpy 
https://docs.python.org/3.5/contents.html
https://docs.scipy.org/doc/numpy/reference/index.html


In [28]:
# Numpy "arrays"
# A numpy array is a grid of values - all of the same type
# and is indexed by a *TUPLE* of nonnegative integers
# The number of dimensions is the "rank" of the array
# the *shape* of the array is a tuple of integers giving the
# size of the array along each dimension.

# numpy arrays can be created from nested Python lists
import numpy as np
b = np.array([[1,2,3],[4,5,6]])
print(type(b))
print(b.shape)
print(b[0:1,0:1])

b = np.zeros(3, dtype = np.float32 )
b = np.zeros(3, dtype = type(b[0,0]))
#Ypred = np.zeros(num_test, dtype = type(self.ytr[0]))
print("type--->", type(b[0]))

b = np.zeros((2,2))
b = np.ones((1,2))
b = np.full((2,2),7)
b = np.eye(2)
b = np.random.random((2,2))



<class 'numpy.ndarray'>
(2, 3)
[[1]]


IndexError: too many indices for array

## Numpy Array Indexing

In [135]:
# Numpy Array Indexing
# Numpy arrays can be sliced.
# You must specify a slice for each dimension
a = np.array([[1,2,3,4],[5,6,7,8],[9,0,1,2]])
# pull out first 2 rows and 2 columns
print(a[:2, :2])

## a slice of an array is a reference into the original data
## so modifying it modifies he original data
b = a[:2, :2]
print(a)
print(b)
b[:] = [[80,81],[82,83]]   ### b is still a numpy array
print(a)
print(b)

### note - this constructs a *NEW* "b" which is a Python list!!!
b = [[90,91],[92,93]]
print(a)
print(b)

[[1 2]
 [5 6]]
[[1 2 3 4]
 [5 6 7 8]
 [9 0 1 2]]
[[1 2]
 [5 6]]
[[80 81  3  4]
 [82 83  7  8]
 [ 9  0  1  2]]
[[80 81]
 [82 83]]
[[80 81  3  4]
 [82 83  7  8]
 [ 9  0  1  2]]
[[90, 91], [92, 93]]


## Numpy Integer Array Indexing

In [138]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

# An example of integer array indexing.
# The returned array will have shape (3,) and
print(a[[0, 1, 2], [0, 1, 0]])  # Prints "[1 4 5]"

[[1 2]
 [3 4]
 [5 6]]
[1 4 5]


In [159]:
# Numpy Datatypes
import numpy as np
x = np.array([1,2])
print(x.dtype)

x = np.array([1.0, 2.3])
print(x.dtype)

x = np.array([3,4], dtype=np.int64)
print(x.dtype)

y = np.array(["foo","barrr"], dtype=np.character)
print(y)
print(y.dtype)


int32
float64
int64
[b'foo' b'barrr']
|S5


In [148]:
# Numpy Array Math
# Basic math functions operate in element-wise on arrays
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
print(x.shape)
print(y.shape)
print(x+y)
print(x*y)
print(x/y)

(2, 2)
(2, 2)
[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[ 0.2         0.33333333]
 [ 0.42857143  0.5       ]]


In [149]:
# Numpy matrix inner ("dot") product
import numpy as np

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

# Matrix / matrix product; both produce the rank 2 array
# [[19 22]
#  [43 50]]
print(x.dot(y))
print(np.dot(x, y))

219
219
[29 67]
[29 67]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [150]:
# Numpy - computation / reduction functions
import numpy as np

x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


In [151]:
# Numpy "transpose"
import numpy as np

x = np.array([[1,2], [3,4]])
print(x)    # Prints "[[1 2]
            #          [3 4]]"
print(x.T)  # Prints "[[1 3]
            #          [2 4]]"

# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    # Prints "[1 2 3]"
print(v.T)  # Prints "[1 2 3]"

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]
[1 2 3]
[1 2 3]


# "Broadcasting"
# "Tile"

In [2]:
import numpy as np
# Numpy "Broadcasting"
# similar to "plate model" in PGMs
# Allows numpy to work with arrays of different shapes
# when performing arithmetic operations
# Such as a smaller array operating multiple times on
# the larger array

# Add the vector v to each row of matrix x
# storing the result in the matrix y
x = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([0,10,0])
y = np.empty_like(x)

#print(x)
#print(v)
#print(y)

# rudimentary loop
for i in range(4):
    y[i,:] = x[i,:] + v

# "tile" to create a vv "stack" of v's - then add
vv = np.tile(v, [4,1])
y = x + vv
print(y)

# "broadcasting" allows us to perform this computation
# without creating copies of v
print(x.shape)
print(v.shape)
y = x + v
print(y)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 0 10  0]
[[0 0 0]
 [0 0 0]
 [0 0 0]
 [0 0 0]]
[[ 1 12  3]
 [ 4 15  6]
 [ 7 18  9]
 [10 21 12]]
(4, 3)
(3,)
[[ 1 12  3]
 [ 4 15  6]
 [ 7 18  9]
 [10 21 12]]


# The Broadcasting Rule

In [192]:
# In order to broadcast, the size of the trailing axes
# for both arrays in an operation must either be
# the same size or one of them must be one.

# For example
# Lining up the sizes of the trailing axes of these arrays
# according to the broadcast rule shows that they are
# compatible:

#      Image  (3d array): 256 x 256 x 3
#      Scale  (1d array):             3
#      Result (3d array): 256 x 256 x 3

# In the following example, both the A and B arrays have
# axes with length one that are expanded to a larger size
# in a broadcast operation.

#      A      (4d array):  8 x 1 x 6 x 1
#      B      (3d array):      7 x 1 x 5
#      Result (4d array):  8 x 7 x 6 x 5
        
        


# If the arrays do not have the same rank, prepend the shape
# of the lower rank array with 1s until both shapes have the
# same length.
# The two arrays are said to be compatible in a dimension if
# they have the same size in the dimension, or if one of the
# arrays has size 1 in that dimension.
# The arrays can be broadcast together if they are compatible
# in all dimensions.
# After broadcasting, each array behaves as if it had shape
# equal to the elementwise maximum of shapes of the two #input arrays.
# In any dimension where one array had size 1 and the other
# array had size greater than 1, the first array behaves as
# if it were copied along that dimension
#
# example:
x = np.ones((6,5), dtype=np.int32) * 5
print(x)
print(x.dtype)

v = np.ones((5), dtype=np.int32)
print(v)

y = x + v
print(y)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]
int32
[1 1 1 1 1]
[[6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]
 [6 6 6 6 6]]


In [199]:
# Numpy "newaxis"
# Here the newaxis operator inserts a new axis
# into a, making it a two-dimensional 4x1 array.
# Figure 4 illustrates the stretching of both arrays to 
# produce the desired 4x3 output array.

# a is [4]
# b is [3]
#to "broadcast" we need  aa (2d array)  4 x 1
#                   and   b (1d array)      3
#                result     (2d array)  4 x 3

from numpy import array, newaxis
a = array([0.0,10.0,20.0,30.0])
b = array([1.0,2.0,3.0])
print(a)
print(b)
aa = a[:,newaxis]
print(aa)
a[:,newaxis] + b
#array([[  1.,   2.,   3.],
#       [ 11.,  12.,  13.],
#       [ 21.,  22.,  23.],
#       [ 31.,  32.,  33.]])

[  0.  10.  20.  30.]
[ 1.  2.  3.]
[[  0.]
 [ 10.]
 [ 20.]
 [ 30.]]


array([[  1.,   2.,   3.],
       [ 11.,  12.,  13.],
       [ 21.,  22.,  23.],
       [ 31.,  32.,  33.]])

In [211]:
# Example 5 from:
# http://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc
#
# Figure 5: The basic operation of vector quantization
# calculates the distance between an object to be classified,
# the dark square, and multiple known codes, the gray
# circles. In this simple case, the codes represent
# individual classes. More complex cases use multiple
# codes per class.
from numpy import array, argmin, sqrt, sum
observation = array([111.0,188.0])
codes = array([[102.0, 203.0],
                [132.0, 193.0],
                [45.0, 155.0],
                [57.0, 173.0]])
# here is the broadcast
diff = codes - observation
#print(diff)
#print(diff**2)
#print(sum(diff**2,axis=-1))
#print(sum(diff**2))
dist = sqrt(sum(diff**2,axis=-1))
nearest = argmin(dist)
print(nearest)

0


In [212]:
# Example 6 from
# http://scipy.github.io/old-wiki/pages/EricsBroadcastingDoc

# observations = 10x3
# codebook     = 5x3

# convert above
# obs[NewAxis,:,:]
# book[:,NewAxis,:]
# sqrt(sum(diff**2,axis=-1))

# results in:
# observations = 10x3  ->   1 x 10 x 3
# codebook     = 5x3   ->   5 x  1 x 3
# result               ->   5 x 10 x 3


In [229]:
# Additional Numpy "Broadcast" examples from
# http://cs231n.github.io/python-numpy-tutorial/

import numpy as np

# Compute outer product of vectors
x = np.array([[1,2,3], [4,5,6]])
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
ww = w[:,newaxis]      # ww has shape (2,1)
print(x + ww)

#from numpy import array, newaxis
#a = array([0.0,10.0,20.0,30.0])
#b = array([1.0,2.0,3.0])
#print(a)
#print(b)
#aa = a[:,newaxis]


[[ 5  6  7]
 [ 9 10 11]]


# SciPy

In [ ]:
# Numpy provides high performance multidimensional arrays
# and basic tools to compute and manipulate these.
# SciPy builds on this with functions that operate on
# on Numpy arrays and are useful for different types of
# scientific and engineering applications

In [237]:
# SciPy Image Operations
from scipy.misc import imread, imsave, imresize

# Read a JPEG image into a numpy array
#img = imread('assets/cat.jpg')
img = imread('./cs231n.github.io/assets/cat.jpg')
print(img.dtype, img.shape)  # Prints "uint8 (400, 248, 3)"

# We can tint the image by scaling each of the color channels
# by a different scalar constant. The image has shape (400, 248, 3);
# we multiply it by the array [1, 0.95, 0.9] of shape (3,);
# numpy broadcasting means that this leaves the red channel unchanged,
# and multiplies the green and blue channels by 0.95 and 0.9
# respectively.
img_tinted = img * [1, 0.95, 0.9]

# Resize the tinted image to be 300 by 300 pixels.
img_tinted = imresize(img_tinted, (200, 150))

# Write the tinted image back to disk
#imsave('assets/cat_tinted.jpg', img_tinted)
imsave('./cs231n.github.io/assets/cat2.jpg', img_tinted)




uint8 (300, 300, 3)


In [240]:
# SciPy - Distance Between Points 
# pdist - also see cdist

import numpy as np
from scipy.spatial.distance import pdist, squareform

# create array where each row is a point in 2D space
x = np.array([[0, 1], [1, 0], [2, 0]])
print(x)

# Compute the Euclidean distance between all rows of x.
# d[i, j] is the Euclidean distance between x[i, :] and x[j, :],
# and d is the following array:
# [[ 0.          1.41421356  2.23606798]
#  [ 1.41421356  0.          1.        ]
#  [ 2.23606798  1.          0.        ]]
y = pdist(x,'euclidean')
print(y)
print(squareform(y))

#d = squareform(pdist(x, 'euclidean'))
#print(d)



[[0 1]
 [1 0]
 [2 0]]
[ 1.41421356  2.23606798  1.        ]
[[ 0.          1.41421356  2.23606798]
 [ 1.41421356  0.          1.        ]
 [ 2.23606798  1.          0.        ]]


# Matplotlib 

In [243]:
# Matplotlib is a plotting library
# plotting ...

import numpy as np
import matplotlib.pyplot as plt

# Compute the x and y coordinates for points on a sine curve
x = np.arange(0,3*np.pi, 0.1)
y = np.sin(x)

# Plot the points using matplotlib
plt.plot(x,y)
plt.show()

### Add multiple lines, legend, title, axis labels...
import numpy as np
import matplotlib.pyplot as plt

# Compute the x and y coordinates for points on sine and cosine curves
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

# Plot the points using matplotlib
plt.plot(x, y_sin)
plt.plot(x, y_cos)
plt.xlabel('x axis label')
plt.ylabel('y axis label')
plt.title('Sine and Cosine')
plt.legend(['Sine', 'Cosine'])
plt.show()

In [244]:
# Subplots
import numpy as np
import matplotlib.pyplot as plt

# Compute the x and y coordinates for points on sine and cosine curves
x = np.arange(0, 3 * np.pi, 0.1)
y_sin = np.sin(x)
y_cos = np.cos(x)

# Set up a subplot grid that has height 2 and width 1,
# and set the first such subplot as active.
plt.subplot(2, 1, 1)

# Make the first plot
plt.plot(x, y_sin)
plt.title('Sine')

# Set the second subplot as active, and make the second plot.
plt.subplot(2, 1, 2)
plt.plot(x, y_cos)
plt.title('Cosine')

# Show the figure.
plt.show()

In [6]:
# Images
# use "imshow" to show images.
import numpy as np
from scipy.misc import imread, imresize
import matplotlib.pyplot as plt

img = imread('./cs231n.github.io/assets/cat.jpg')

img_tinted = img * [1, 0.6, 0.7]

# Show the original image
plt.subplot(1, 2, 1)
plt.imshow(img)

# Show the tinted image
plt.subplot(1, 2, 2)

# A slight gotcha with imshow is that it might give strange results
# if presented with data that is not uint8. To work around this, we
# explicitly cast the image to uint8 before displaying it.
plt.imshow(np.uint8(img_tinted))
plt.show()